import { useState, useEffect } from "react";
import { useParams, Link } from "react-router";
import {
  MapPin,
  Clock,
  DollarSign,
  Utensils,
  Camera,
  Coffee,
  Sunrise,
  Sun,
  Sunset,
  Moon,
  ChevronDown,
  ChevronUp,
  Sparkles,
  Navigation,
  Star,
  Loader2,
  Settings2,
  ArrowLeft,
  Search,
  Save,
  Share2,
  Users
} from "lucide-react";
import { toast } from "sonner";
import { generateAiItinerary, getAiLimit } from "../../../api/aiApi";
import { getDestinationDetails } from "@/api/destinationsApi";
import type { AiGenerateItineraryResponse, AiActivity } from "../../../types/ai";
import type { DestinationDto } from "@/types/destinations";
import { createItinerary, getItinerary } from "@/api/itinerariesApi";
import { useNavigate, useLocation } from "react-router";
import { useAuth } from "../../../contexts/AuthContext";

export function ItineraryPlannerPage() {
  const { id } = useParams();
  const destinationId = Number(id);
  const location = useLocation();
  const stateDays = (location.state as any)?.days;
  const autoGenerate = (location.state as any)?.autoGenerate;
  const budgetVND = (location.state as any)?.budgetVND;
  const itineraryId = (location.state as any)?.itineraryId;

  const [destination, setDestination] = useState<DestinationDto | null>(null);
  const [itineraryData, setItineraryData] = useState<AiGenerateItineraryResponse | null>(null);
  const [expandedDay, setExpandedDay] = useState<number | null>(1);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isInitialLoad, setIsInitialLoad] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [savedItineraryId, setSavedItineraryId] = useState<number | null>(itineraryId || null);
  const navigate = useNavigate();

  const { isAuthenticated } = useAuth();
  const [aiLimit, setAiLimit] = useState<{ used: number; limit: number; remaining: number } | null>(null);

  const fetchLimit = () => {
    if (isAuthenticated) {
      getAiLimit()
        .then(data => setAiLimit(data))
        .catch(err => console.error("Failed to load AI limit", err));
    }
  };

  useEffect(() => {
    fetchLimit();
  }, [isAuthenticated]);

  // Form State
  const [days, setDays] = useState<number>(() => {
    if (stateDays) return stateDays;
    const aiFormStr = localStorage.getItem("ai_formData");
    if (aiFormStr) {
      try {
        const aiForm = JSON.parse(aiFormStr);
        if (aiForm.days) return Number(aiForm.days);
      } catch (e) { }
    }
    return 3;
  });

  const [travelStyle, setTravelStyle] = useState<string>(() => {
    const aiFormStr = localStorage.getItem("ai_formData");
    if (aiFormStr) {
      try {
        const aiForm = JSON.parse(aiFormStr);
        if (aiForm.travelStyle) return aiForm.travelStyle;
        if (aiForm.interests) {
          if (aiForm.interests.includes("beach")) return "Relaxation";
          if (aiForm.interests.includes("mountain") || aiForm.interests.includes("nature")) return "Adventure";
        }
      } catch (e) { }
    }
    return "Budget";
  });

  useEffect(() => {
    if (!destinationId) return;
    const loadDest = async () => {
      try {
        if (itineraryId) {
          const trip = await getItinerary(itineraryId);
          if (trip && trip.details) {
            // Group details by DayNumber
            const daysMap = new Map<number, AiActivity[]>();
            trip.details.forEach(d => {
              const activities = daysMap.get(d.dayNumber) || [];
              activities.push({
                time: d.timeSlot,
                description: d.activityDescription,
                estimatedCostVND: d.estimatedCostVND
              });
              daysMap.set(d.dayNumber, activities);
            });

            const aiDays = Array.from(daysMap.entries())
              .sort((a, b) => a[0] - b[0])
              .map(([dayNumber, activities]) => ({
                dayNumber,
                activities
              }));

            setItineraryData({
              title: trip.tripName,
              totalDays: aiDays.length,
              days: aiDays
            });
            setDays(aiDays.length);
          }
        } else {
          const cached = localStorage.getItem(`ai_itinerary_${destinationId}`);
          if (cached) {
            try {
              const parsed = JSON.parse(cached);
              if (!autoGenerate || parsed.totalDays === (stateDays || days)) {
                setItineraryData(parsed);
                setHasAutoGenerated(true); // Skip auto-generation
              }
            } catch (e) { }
          }
        }

        const dest = await getDestinationDetails(destinationId);
        setDestination(dest);
      } catch (e) {
        console.error(e);
      } finally {
        setIsInitialLoad(false);
      }
    };
    loadDest();
  }, [destinationId]);

  useEffect(() => {
    if (autoGenerate && destination && !isInitialLoad && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      handleGenerate();
    }
  }, [autoGenerate, destination, isInitialLoad, hasAutoGenerated]);

  const handleGenerate = async () => {
    if (!destination) return;
    setIsLoading(true);
    try {
      const data = await generateAiItinerary({
        destinationID: destination.destinationID,
        days,
        travelStyle,
        budgetVND
      });
      setItineraryData(data);
      localStorage.setItem(`ai_itinerary_${destination.destinationID}`, JSON.stringify(data));
      setExpandedDay(1);
      setSavedItineraryId(null);
      fetchLimit();
    } catch (error: any) {
      console.error("Failed to generate", error);
      const status = error?.response?.status;
      const serverMsg = error?.response?.data;

      if (status === 403) {
        toast.error(typeof serverMsg === 'string' ? serverMsg : "Bạn đã sử dụng hết lượt tạo lịch trình bằng AI.", {
          duration: 5000,
        });
      } else if (status === 401) {
        toast.error("Bạn cần đăng nhập để sử dụng tính năng AI.");
      } else {
        toast.error("Có lỗi xảy ra khi tạo lịch trình. Vui lòng thử lại.");
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleSaveItinerary = async () => {
    if (!itineraryData || !destination) return;
    setIsSaving(true);
    try {
      const startDate = new Date();
      startDate.setDate(startDate.getDate() + 1); // Start tomorrow by default
      const endDate = new Date(startDate);
      endDate.setDate(endDate.getDate() + itineraryData.totalDays - 1);

      const details = itineraryData.days.flatMap(d =>
        d.activities.map(a => ({
          destinationID: destination.destinationID,
          dayNumber: d.dayNumber,
          timeSlot: a.time,
          activityDescription: a.description,
          estimatedCostVND: a.estimatedCostVND
        }))
      );

      const totalCost = details.reduce((sum, item) => sum + item.estimatedCostVND, 0);

      const response = await createItinerary({
        tripName: `Chuyến đi ${destination.name} ${itineraryData.totalDays} ngày`,
        startDate: startDate.toISOString(),
        endDate: endDate.toISOString(),
        totalBudgetEstimatedVND: totalCost,
        details: details
      });

      setSavedItineraryId(response.itineraryID);
      toast.success("Đã lưu lịch trình thành công!");
    } catch (error) {
      console.error("Failed to save itinerary", error);
      toast.error("Có lỗi xảy ra khi lưu lịch trình.");
    } finally {
      setIsSaving(false);
    }
  };

  // Helper to infer icon/period from time string
  const inferPeriodInfo = (timeStr: string, description: string) => {
    const lowerTime = timeStr.toLowerCase();
    const lowerDesc = description.toLowerCase();

    let period = "morning";
    if (lowerTime.includes("pm")) {
      const hourMatch = lowerTime.match(/(\d+)/);
      if (hourMatch) {
        const hour = parseInt(hourMatch[1]);
        if (hour < 5 || hour === 12) period = "afternoon";
        else period = "evening";
      }
    } else if (lowerTime.includes("night") || lowerTime.includes("evening")) {
      period = "evening";
    }

    let icon = Navigation;
    if (lowerDesc.includes("eat") || lowerDesc.includes("breakfast") || lowerDesc.includes("lunch") || lowerDesc.includes("dinner") || lowerDesc.includes("food") || lowerDesc.includes("restaurant")) {
      icon = Utensils;
    } else if (lowerDesc.includes("coffee") || lowerDesc.includes("cafe")) {
      icon = Coffee;
    } else if (lowerDesc.includes("temple") || lowerDesc.includes("museum") || lowerDesc.includes("explore") || lowerDesc.includes("visit")) {
      icon = Camera;
    }

    return { period, icon };
  };

  const getPeriodIcon = (period: string) => {
    switch (period) {
      case "morning": return Sunrise;
      case "afternoon": return Sun;
      case "evening": return Sunset;
      default: return Moon;
    }
  };

  const getPeriodColor = (period: string) => {
    switch (period) {
      case "morning": return "from-orange-400 to-yellow-400";
      case "afternoon": return "from-yellow-400 to-orange-500";
      case "evening": return "from-purple-500 to-pink-500";
      default: return "from-indigo-500 to-purple-600";
    }
  };

  if (isInitialLoad) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="w-12 h-12 animate-spin text-primary" />
      </div>
    );
  }

  if (!destination) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-background">
        <h2 className="text-2xl font-bold mb-4">Không tìm thấy điểm đến</h2>
        <Link to="/discover" className="text-primary hover:underline">Quay lại khám phá</Link>
      </div>
    );
  }

  const totalCost = itineraryData?.days.reduce(
    (sum, day) => sum + day.activities.reduce((daySum, activity) => daySum + activity.estimatedCostVND, 0),
    0
  ) || 0;

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="bg-gradient-to-br from-primary to-secondary text-white py-12 relative overflow-hidden">
        {/* Glow Effects */}
        <div className="absolute top-0 left-0 w-full h-full overflow-hidden z-0">
          <div className="absolute -top-24 -left-24 w-96 h-96 bg-white/10 rounded-full blur-3xl"></div>
          <div className="absolute bottom-0 right-0 w-96 h-96 bg-black/10 rounded-full blur-3xl"></div>
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <Link to={`/destination/${destination.destinationID}`} className="inline-flex items-center gap-2 text-white/80 hover:text-white mb-6 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            <span>Quay lại {destination.name}</span>
          </Link>

          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center shadow-lg">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-3xl md:text-5xl font-bold tracking-tight">Lập lịch trình bằng AI</h1>
          </div>
          <p className="text-white/90 max-w-2xl mb-8 text-lg">
            Để AI thiết kế hành trình phù hợp cho chuyến đi đến <span className="font-semibold">{destination.name}</span>
          </p>

          {!itineraryData && (
            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20 shadow-2xl max-w-2xl">
              <h3 className="text-xl font-semibold mb-4 flex items-center gap-2">
                <Settings2 className="w-5 h-5" />
                Tùy chỉnh chuyến đi
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
                <div>
                  <label className="block text-sm text-white/80 mb-2">Số ngày</label>
                  <select
                    value={days}
                    onChange={(e) => setDays(Number(e.target.value))}
                    className="w-full bg-white/20 border border-white/30 rounded-xl px-4 py-3 text-white outline-none focus:ring-2 focus:ring-white/50"
                  >
                    {Array.from({ length: 14 }, (_, i) => i + 1).map(num => (
                      <option key={num} value={num} className="text-foreground bg-background">{num} ngày</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm text-white/80 mb-2">Phong cách du lịch</label>
                  <select
                    value={travelStyle}
                    onChange={(e) => setTravelStyle(e.target.value)}
                    className="w-full bg-white/20 border border-white/30 rounded-xl px-4 py-3 text-white outline-none focus:ring-2 focus:ring-white/50"
                  >
                    <option value="Budget" className="text-foreground bg-background">Tiết kiệm / backpacking</option>
                    <option value="Luxury" className="text-foreground bg-background">Cao cấp / thoải mái</option>
                    <option value="Adventure" className="text-foreground bg-background">Phiêu lưu / khám phá</option>
                    <option value="Relaxation" className="text-foreground bg-background">Nghỉ dưỡng / biển</option>
                  </select>
                </div>
              </div>
              <button
                onClick={handleGenerate}
                disabled={isLoading}
                className="w-full py-4 bg-white text-primary rounded-xl font-bold text-lg hover:shadow-[0_0_20px_rgba(255,255,255,0.4)] transition-all disabled:opacity-70 flex items-center justify-center gap-2"
              >
                {isLoading ? <Loader2 className="w-6 h-6 animate-spin" /> : <Sparkles className="w-6 h-6" />}
                {isLoading ? "AI đang tạo lịch trình cho bạn..." : "Tạo lịch trình"}
              </button>

              {isAuthenticated && aiLimit && (
                <div className="mt-4 pt-4 border-t border-white/20 flex items-center justify-between text-xs text-white/95">
                  <div className="flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-yellow-300" />
                    <span>Lượt sử dụng AI hôm nay:</span>
                    <span className="font-semibold text-white">{aiLimit.remaining}/{aiLimit.limit} còn lại</span>
                  </div>
                  <div className="w-24 sm:w-32 h-1.5 bg-white/20 rounded-full overflow-hidden">
                    <div 
                      className={`h-full rounded-full transition-all duration-500 ${
                        aiLimit.remaining === 0 ? "bg-red-400" :
                        aiLimit.remaining === 1 ? "bg-yellow-400" : "bg-green-400"
                      }`}
                      style={{ width: `${(aiLimit.remaining / aiLimit.limit) * 100}%` }}
                    />
                  </div>
                </div>
              )}
            </div>
          )}

          {itineraryData && (
            <div className="flex flex-wrap gap-4 text-sm mt-4">
              <div className="flex items-center gap-2 px-5 py-2.5 bg-white/20 backdrop-blur-sm rounded-full border border-white/10">
                <MapPin className="w-4 h-4" />
                <span className="font-medium">{destination.name}</span>
              </div>
              <div className="flex items-center gap-2 px-5 py-2.5 bg-white/20 backdrop-blur-sm rounded-full border border-white/10">
                <Clock className="w-4 h-4" />
                <span className="font-medium">{itineraryData.totalDays} ngày • {travelStyle}</span>
              </div>
              <div className="flex items-center gap-2 px-5 py-2.5 bg-white/20 backdrop-blur-sm rounded-full border border-white/10">
                <DollarSign className="w-4 h-4" />
                <span className="font-medium">{new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(totalCost)} ước tính</span>
              </div>
              {isAuthenticated && aiLimit && (
                <div className="flex items-center gap-2.5 px-5 py-2.5 bg-white/20 backdrop-blur-sm rounded-full border border-white/10 text-xs">
                  <Sparkles className="w-4 h-4 text-yellow-300 animate-pulse" />
                  <span>AI: {aiLimit.remaining}/{aiLimit.limit}</span>
                  <div className="w-16 h-1.5 bg-white/20 rounded-full overflow-hidden">
                    <div 
                      className={`h-full rounded-full transition-all duration-500 ${
                        aiLimit.remaining === 0 ? "bg-red-400" :
                        aiLimit.remaining === 1 ? "bg-yellow-400" : "bg-green-400"
                      }`}
                      style={{ width: `${(aiLimit.remaining / aiLimit.limit) * 100}%` }}
                    />
                  </div>
                </div>
              )}
              <button onClick={() => {
                setItineraryData(null);
                if (destination) localStorage.removeItem(`ai_itinerary_${destination.destinationID}`);
              }} className="flex items-center gap-2 px-5 py-2.5 bg-black/20 hover:bg-black/40 backdrop-blur-sm rounded-full transition-colors border border-white/10">
                <Settings2 className="w-4 h-4" />
                <span>Tạo lại</span>
              </button>
            </div>
          )}
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {!itineraryData && !isLoading && (
          <div className="text-center py-20 bg-card rounded-2xl border border-border/50 shadow-sm mt-8">
            <Sparkles className="w-16 h-16 text-primary/40 mx-auto mb-4" />
            <h2 className="text-2xl font-semibold text-foreground mb-2">Sẵn sàng lên kế hoạch?</h2>
            <p className="text-muted-foreground max-w-md mx-auto">Chọn sở thích ở phía trên để AI tạo lịch trình cá nhân hóa riêng cho {destination.name}.</p>
          </div>
        )}

        {isLoading && (
          <div className="text-center py-32 space-y-6">
            <div className="relative w-24 h-24 mx-auto">
              <div className="absolute inset-0 border-4 border-primary/20 rounded-full"></div>
              <div className="absolute inset-0 border-4 border-primary rounded-full border-t-transparent animate-spin"></div>
              <Sparkles className="absolute inset-0 m-auto w-8 h-8 text-primary animate-pulse" />
            </div>
            <h3 className="text-2xl font-bold text-foreground">Đang xây dựng hành trình phù hợp...</h3>
            <p className="text-muted-foreground animate-pulse">AI đang phân tích điểm tham quan, thời gian di chuyển và tuyến đường tối ưu tại {destination.name}.</p>
          </div>
        )}

        {itineraryData && (
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
            {/* Timeline Navigation */}
            <div className="lg:col-span-1">
              <div className="sticky top-20 bg-card rounded-2xl shadow-lg p-6 border border-border/50">
                <h3 className="font-bold mb-4 text-lg">Tổng quan chuyến đi</h3>
                <div className="space-y-2">
                  {itineraryData.days.map((day) => (
                    <button
                      key={day.dayNumber}
                      onClick={() => setExpandedDay(day.dayNumber)}
                      className={`w-full text-left px-4 py-3 rounded-xl transition-all flex justify-between items-center ${expandedDay === day.dayNumber
                        ? "bg-primary text-white shadow-md"
                        : "bg-background border border-border/50 hover:bg-primary/5 dark:hover:bg-primary/10"
                        }`}
                    >
                      <div>
                        <div className="font-semibold">Ngày {day.dayNumber}</div>
                        <div className={`text-xs mt-1 ${expandedDay === day.dayNumber ? "text-white/80" : "text-muted-foreground"}`}>
                          {day.activities.length} hoạt động
                        </div>
                      </div>
                      <ChevronRightIcon className={`w-4 h-4 ${expandedDay === day.dayNumber ? "text-white" : "text-muted-foreground opacity-50"}`} />
                    </button>
                  ))}
                </div>

                {/* Quick Stats */}
                <div className="mt-6 pt-6 border-t border-border space-y-4">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">Tổng số ngày</span>
                    <span className="font-semibold bg-primary/10 text-primary dark:bg-primary/20 px-2 py-1 rounded-md">{itineraryData.totalDays}</span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">Hoạt động</span>
                    <span className="font-semibold bg-primary/10 text-primary dark:bg-primary/20 px-2 py-1 rounded-md">
                      {itineraryData.days.reduce((sum, day) => sum + day.activities.length, 0)}
                    </span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-muted-foreground">Chi phí ước tính</span>
                    <span className="font-bold text-primary">
                      {new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(totalCost)}
                    </span>
                  </div>

                  <div className="pt-4 flex flex-col gap-3">
                    <button
                      onClick={handleSaveItinerary}
                      disabled={isSaving || savedItineraryId !== null}
                      className="w-full flex items-center justify-center gap-2 bg-primary text-white py-2.5 rounded-xl font-semibold hover:bg-primary/90 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                      {savedItineraryId ? "Đã lưu lịch trình" : "Lưu lịch trình"}
                    </button>

                    <button
                      onClick={() => {
                        const summaryText = `Mình vừa tạo lịch trình đi ${destination.name} trong ${itineraryData.totalDays} ngày cực chi tiết bằng AI của TravelHub! Mọi người tham khảo nhé 👇\n\n` +
                          `📍 Điểm đến: ${destination.name}\n` +
                          `⏱️ Thời gian: ${itineraryData.totalDays} ngày\n` +
                          `💰 Dự kiến: ${new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(totalCost)}\n\n` +
                          `📋 Chi tiết:\n` +
                          itineraryData.days.map(d => `- Ngày ${d.dayNumber}: ${d.activities.length} hoạt động`).join('\n');

                        navigate('/community', { state: { initialPostContent: summaryText } });
                      }}
                      className="w-full flex items-center justify-center gap-2 bg-blue-50 dark:bg-blue-500/10 text-blue-600 dark:text-blue-400 py-2.5 rounded-xl font-semibold hover:bg-blue-100 dark:hover:bg-blue-500/20 transition-all border border-blue-100 dark:border-blue-500/20"
                    >
                      <Share2 className="w-4 h-4" />
                      Chia sẻ lên cộng đồng
                    </button>

                    <Link
                      to={`/tours/search?destinationId=${destinationId}`}
                      className="w-full flex items-center justify-center gap-2 bg-orange-50 dark:bg-orange-500/10 text-orange-600 dark:text-orange-400 py-2.5 rounded-xl font-semibold hover:bg-orange-100 dark:hover:bg-orange-500/20 transition-all border border-orange-100 dark:border-orange-500/20"
                    >
                      <Search className="w-4 h-4" />
                      Tìm tour phù hợp
                    </Link>

                    <button
                      onClick={() => {
                        const summaryText = `Mình đang tìm Hướng dẫn viên cho lịch trình đi ${destination.name} trong ${itineraryData.totalDays} ngày!\n\n` +
                          `📍 Điểm đến: ${destination.name}\n` +
                          `⏱️ Thời gian: ${itineraryData.totalDays} ngày\n` +
                          `💰 Ngân sách dự kiến: ${new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(totalCost)}\n\n` +
                          `📋 Chi tiết lịch trình:\n` +
                          itineraryData.days.map(d => `- Ngày ${d.dayNumber}: ${d.activities.length} hoạt động`).join('\n');

                        navigate('/community', { state: { initialPostContent: summaryText, postType: 'GuideRequest' } });
                      }}
                      className="w-full flex items-center justify-center gap-2 bg-green-50 dark:bg-green-500/10 text-green-600 dark:text-green-400 py-2.5 rounded-xl font-semibold hover:bg-green-100 dark:hover:bg-green-500/20 transition-all border border-green-100 dark:border-green-500/20"
                    >
                      <Users className="w-4 h-4" />
                      Tìm Hướng dẫn viên
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Itinerary Details */}
            <div className="lg:col-span-3 space-y-8">
              {itineraryData.days.map((day) => (
                <div key={day.dayNumber} className={`bg-card rounded-2xl shadow-lg overflow-hidden border border-border/50 transition-all duration-300 ${expandedDay === day.dayNumber ? 'ring-2 ring-primary/20' : ''}`}>
                  {/* Day Header */}
                  <button
                    onClick={() => setExpandedDay(expandedDay === day.dayNumber ? null : day.dayNumber)}
                    className="w-full bg-gradient-to-r from-primary to-secondary text-white p-6 flex items-center justify-between hover:opacity-95 transition-opacity"
                  >
                    <div className="text-left flex items-center gap-4">
                      <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm border border-white/20">
                        <span className="text-xl font-bold">{day.dayNumber}</span>
                      </div>
                      <div>
                        <div className="text-xl font-bold mb-1">Ngày {day.dayNumber}</div>
                        <div className="text-white/80 text-sm">{day.activities.length} hoạt động đã lên kế hoạch</div>
                      </div>
                    </div>
                    {expandedDay === day.dayNumber ? (
                      <ChevronUp className="w-6 h-6 bg-white/20 rounded-full p-1" />
                    ) : (
                      <ChevronDown className="w-6 h-6 bg-white/20 rounded-full p-1" />
                    )}
                  </button>

                  {/* Day Activities */}
                  {expandedDay === day.dayNumber && (
                    <div className="p-6 bg-background">
                      <div className="relative">
                        {/* Timeline Line */}
                        <div className="absolute left-6 top-6 bottom-6 w-0.5 bg-gradient-to-b from-primary/80 via-secondary/80 to-purple-500/80 rounded-full" />

                        {/* Activities */}
                        <div className="space-y-8 relative py-4">
                          {day.activities.map((activity, index) => {
                            const { period, icon: ActivityIcon } = inferPeriodInfo(activity.time, activity.description);
                            const PeriodIcon = getPeriodIcon(period);

                            return (
                              <div key={index} className="relative pl-16 group">
                                {/* Timeline Dot */}
                                <div
                                  className={`absolute left-3 w-7 h-7 rounded-full bg-gradient-to-br ${getPeriodColor(
                                    period
                                  )} flex items-center justify-center shadow-md ring-4 ring-background z-10 group-hover:scale-110 transition-transform`}
                                >
                                  <PeriodIcon className="w-3.5 h-3.5 text-white" />
                                </div>

                                {/* Activity Card */}
                                <div className="bg-card rounded-xl p-5 shadow-sm border border-border/60 hover:shadow-md hover:border-primary/30 transition-all group-hover:-translate-y-1">
                                  <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 mb-3">
                                    <div className="flex items-start gap-4">
                                      <div className="w-12 h-12 rounded-xl bg-primary/5 border border-primary/10 flex items-center justify-center shadow-inner flex-shrink-0">
                                        <ActivityIcon className="w-6 h-6 text-primary" />
                                      </div>
                                      <div>
                                        <div className="text-sm font-semibold text-primary mb-1 flex items-center gap-2">
                                          <Clock className="w-3.5 h-3.5" />
                                          {activity.time}
                                        </div>
                                        <div className="font-medium text-foreground text-base leading-snug">
                                          {activity.description}
                                        </div>
                                      </div>
                                    </div>
                                    <div className="text-right flex-shrink-0 sm:ml-4 bg-primary/5 dark:bg-primary/10 px-3 py-2 rounded-lg self-start sm:self-auto border border-primary/10 dark:border-primary/20">
                                      <div className="text-xs text-muted-foreground uppercase tracking-wider font-semibold mb-1">Chi phí ước tính</div>
                                      <div className="font-bold text-foreground">
                                        {activity.estimatedCostVND === 0
                                          ? <span className="text-green-600">Miễn phí</span>
                                          : new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(activity.estimatedCostVND)
                                        }
                                      </div>
                                      {activity.estimatedCostVND > 0 && (
                                        <Link
                                          to="/compare"
                                          className="mt-2 inline-flex items-center justify-center gap-1.5 w-full bg-primary/10 hover:bg-primary/20 text-primary text-xs font-semibold py-1.5 px-3 rounded-md transition-colors"
                                        >
                                          <Search className="w-3.5 h-3.5" />
                                          Compare Prices
                                        </Link>
                                      )}
                                    </div>
                                  </div>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>

                      {/* Day Summary */}
                      <div className="mt-8 pt-6 border-t border-border flex items-center justify-between bg-primary/5 dark:bg-primary/10 -mx-6 -mb-6 px-6 py-4">
                        <div className="text-sm font-medium text-primary flex items-center gap-2">
                          <span>Tổng trong ngày:</span>
                          <span className="font-bold">
                            {new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(
                              day.activities.reduce((sum, activity) => sum + activity.estimatedCostVND, 0)
                            )}
                          </span>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              ))}

              {/* AI Recommendations Notice */}
              <div className="bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-950/20 dark:to-blue-950/20 rounded-2xl p-6 border border-purple-200 dark:border-purple-800">
                <div className="flex items-start gap-3">
                  <div className="w-10 h-10 rounded-full bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center flex-shrink-0 shadow-lg">
                    <Sparkles className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h4 className="font-semibold mb-2 text-purple-900 dark:text-purple-200">Lưu ý từ trợ lý du lịch AI</h4>
                    <p className="text-sm text-purple-800/80 dark:text-purple-300/80 leading-relaxed">
                      Lịch trình này được tạo động dựa trên dữ liệu hiện có của <strong>{destination.name}</strong>, tối ưu theo phong cách <strong>{travelStyle}</strong>. Giá chỉ là ước tính và có thể thay đổi. Bạn nên đặt chỗ ở và hoạt động trước.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function ChevronRightIcon({ className }: { className?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
